---
title: "Publications"
---

::: {style="font-size: 70%; font-style: italic"}
*Electronic copies of papers are provided as a professional courtesy to ensure timely dissemination of academic work for individual, non-commercial purposes. Copyright resides with the respective copyright holders, as stated within each paper. These files may not be re-posted without permission.*
:::

#### [Manuscripts in progress]{.underline}

**Brodie, K.**, Reggev, N., & Krosch, A. (in prep). Stereotype congruence biases social learning.

**Brodie, K.**, Schwitzgebel, E., Nemirow, J., & Cushman, F. (under review). Philosophical arguments can boost charitable giving. [**Online**](https://osf.io/preprints/psyarxiv/5v2md_v1){target="_blank"} \| [**PDF**](files/papers/Charitable_Giving_Manuscript_Preprint.pdf)

Lee, R., **Brodie, K.**, Richardson, J., & Gilovich, T. (revise and resubmit). Glad to help out: Grateful people are more likely to engage in costly prosocial action.

#### [Peer-reviewed publications]{.underline}

Reggev, N., **Brodie, K.**, Cikara, M., & Mitchell, J.P. (2020). Human face-selective cortex does not distinguish between members of a racial outgroup. *ENeuro*, *7*(3). [**Online**](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7266143/){target="_blank"} \| [**PDF**](files/papers/ReggevBrodieCikaraMitchell2020.pdf)
